project:
  type: website
  render:
    - "*.qmd"
    - "lecture/"

website:
  title: "E85"
  navbar:
    right:
      - icon: github
        href: https://github.com/HMC-E85/E85
        aria-label: GitHub

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    highlight-style: ally
    monobackgroundcolor: transparent